name: CI

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          [
            { name: "windows", image: "windows-latest" },
            { name: "macos", image: "macos-latest" },
          ]
    runs-on: ${{ matrix.os.image }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Initialize environment
        uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: npm
          cache-dependency-path: package-lock.json
      - name: Install node modules
        run: npm install
      - name: Presubmit check (e.g. lint, format)
        # do not run this on Windows (it fails and not necessary)
        if: contains(matrix.os.name, 'macos')
        run: npm run presubmit
      - name: Type-checking
        # do not run this on windows (it's redunant)
        if: contains(matrix.os.name, 'macos')
        run: npm run ts
      - name: Build
        run: npm run pre:e2e
      - name: Upload build artifacts
        uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4.6.0
        with:
          name: build-artifacts-${{ matrix.os.name }}
          path: out/
          retention-days: 1

  test:
    needs: build
    strategy:
      fail-fast: false
      matrix:
        os:
          [
            { name: "windows", image: "windows-latest" },
            { name: "macos", image: "macos-latest" },
          ]
        shard: [1, 2, 3, 4]
    runs-on: ${{ matrix.os.image }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Initialize environment
        uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: npm
          cache-dependency-path: package-lock.json
      - name: Install node modules
        run: npm install
      - name: Download build artifacts
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
        with:
          name: build-artifacts-${{ matrix.os.name }}
          path: out/
      - name: Install Chromium browser for Playwright
        run: npx playwright install chromium --with-deps
      - name: Prep test server
        run: cd testing/fake-llm-server && npm install && npm run build && cd -
      - name: E2E tests
        # You can add debug logging to make it easier to see what's failing
        # by adding "DEBUG=pw:browser" in front.
        run: DEBUG=pw:browser npm run e2e -- --shard=${{ matrix.shard }}/4
      - uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4.6.0
        if: failure()
        with:
          name: playwright-report-${{ matrix.os.name }}-shard-${{ matrix.shard }}
          path: playwright-report/
          retention-days: 3
      - uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4.6.0
        if: failure()
        with:
          name: test-results-${{ matrix.os.name }}-shard-${{ matrix.shard }}
          path: test-results/
          retention-days: 3

  merge-reports:
    needs: test
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Initialize environment
        uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: npm
          cache-dependency-path: package-lock.json
      - name: Install node modules
        run: npm install
      - name: Download all test results
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
        with:
          pattern: test-results-*
          path: all-test-results/
          merge-multiple: true
      - name: Merge Playwright reports
        run: npx playwright merge-reports --reporter html ./all-test-results
      - name: Upload merged report
        uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4.6.0
        with:
          name: merged-playwright-report
          path: playwright-report/
          retention-days: 3
